# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"

reviews:
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
    ignore_usernames: []
